### ISSUE TITLE
login not possible

### ISSUE THREAD

**Issue by RobbiXYZ** [adamlove01/nuxt-ssr-secure-website#1]
despite a fresh build i am not able to login as admin or user (no passwords known).

> Admin ?== beautifulHorseHippoAlgebra===9632 ?== $2a$10$sAI76ulPDz2Kud6Aau1AUemMiy7JzW6KD9.SlFCHOWysIb0GCiQp6

How about the passwords of the other clients like "Joel Barish", ...?

Is the verify - system ok?

---
### Answers to @DearPureone
Ubuntu 20.04.3 LTS
openjdk 11.0.11 2021-04-20
node v16.13.0
@vue/cli 4.5.15
mariadb  Ver 15.1 Distrib 10.3.31-MariaDB

---
I changed in "**knexfile.cjs**":
```
    connection: {
      socketPath: process.env.DB_SOCKET,
      /* port: process.env.DB_PORT,
      host: process.env.DB_HOST, */
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      charset: process.env.DB_CHARSET,
      database: process.env.DB_NAME,

```
and in ".**env**":
```
BASE_URL=http://localhost:3000
BROWSER_BASE_URL=http://localhost:3000
TOKEN_AUTH_SECRET=6f3dd6e7005ff901ec4330479363218e61e94fae4a86f072e44db4636b8dd7b2
DB_SOCKET='/var/run/mysqld/mysqld.sock'
DB_NAME=nuxtssr
DB_USER=iamadminuser
DB_PASSWORD=geheim
DB_CLIENT='mysql'
DB_CHARSET='utf8'
```
After errors in the first try then MariaDB worked:
```
npx knex migrate:unlock --knexfile knexfile.cjs
npx knex migrate:latest --knexfile knexfile.cjs
npx knex seed:run --knexfile knexfile.cjs

```

that had generate 3 tables in MariaDB:
- knex_migrations
- knex_migrations_lock
- users 

in MariaDB users table:
```
SELECT * FROM users
id	name	email	password	image	type	status	created_at	updated_at	last_login
1	admin	admin@admin.com	$2a$10$sAI76ulPDz2Kud6Aau1AUemMiy7JzW6KD9.SlFCHOWysIb0GCiQp6		admin	active	2021-11-14 15:12:46	2021-11-14 15:12:46	2021-11-14 15:12:46
2	Joel Barish	joelbarish@mydomain.com	$2a$10$0UlO77GVzXTmF6mlX96HpuDdoQbj0oKzwELKGYN3TxLEYvzzkw4wi		client	active	2021-11-14 15:12:46	2021-11-14 15:12:46	2021-11-14 15:12:46`
...  [25 records]
```
---
but login (like in the demo) not possible, also no Sign up: _Error while creating User. Please try again later._  
The only warn message on the console is "_returning() is not supported by mysql and will not have any effect._ "

**Comment by DearPureone** [comment]
> despite a fresh build i am not able to login as admin or user (no passwords known).
> 
> > Admin ?== beautifulHorseHippoAlgebra===9632 ?== $2a$10$sAI76ulPDz2Kud6Aau1AUemMiy7JzW6KD9.SlFCHOWysIb0GCiQp6
> 
> How about the passwords of the other clients like "Joel Barish", ...?
> 
> Is the verify - system ok?

I've test by this and login just fine
on Postgres & MSSQL
>Admin login
By default you can log in as an Admin user:
Email: admin@admin.com
Password: beautifulHorseHippoAlgebra===9632

What's your database you've use
any error on 
> knex migrate:latest --knexfile knexfile.cjs

or
> knex seed:run --knexfile knexfile.cjs

If no
Try add user data by your self or direct edit password in db

> Is the verify - system ok?

e-mail verify system seem ok
set up  Nodemailer and it can sent verify email to new user register

but look like confirm popup on Sign Up Successful not show as expect after last update
may be it have little conflict on /register endpoint Controller

and on /reset-password look like he forgot to add ' bcrypt function' so user can't login after reset password just add it

that the problem i found after update.

Great Project by the way Hope @adamlove01 continue to finish this.

**Comment by RobbiXYZ** [comment]
And absolute YES: Great Project. I also hope @adamlove01  continue to finish this.

**Comment by DearPureone** [comment]
>but login (like in the demo) not possible, also no Sign up: Error while creating User. Please try again later.
The only warn message on the console is "returning() is not supported by mysql and will not have any effect. "



[returning](https://knexjs.org/#Builder-returning) is not supported by MySQL.


>Utilized by PostgreSQL, MSSQL, and Oracle databases, the returning method specifies which column should be returned by the insert and update methods.

**Comment by adamlove01** [comment]
Sorry for your issue! I will have time to check it out in the next couple days.

**Comment by RobbiXYZ** [comment]
@adamlove01 - is this issue repair-able? What is wrong?

**Comment by adamlove01** [comment]
How did you build it: What database are you using? Is your database running? Did you configure your .env file correctly? Most login issues are due to the database connection.

After setup you can log in to 'admin@admin.com' with password 'beautifulHorseHippoAlgebra===9632'

Then after logging in you can click on the Admin link in the top nav and reset other passwords. BUT you will need to set up your email delivery provider first, according to the link in the readme [Configuring Nodemailer for sending email](https://github.com/adamlove01/nuxt-ssr-secure-website/blob/master/docs/emailConfig.md) . 

If you really want to log in as other users without resets, the password formula is 'name123'. Example: 
User: joelbarish@mydomain.com
Password: joelbarish123

This project is not a demo where all the features "just work" on local but have massive security holes. To run any site with a login on production, you need some kind of email delivery provider. If you click through the code you will see readme files in just about every folder. 

If you can provide dev console and/or server errors and more details about your setup, I will do what I can to help.

**Comment by RobbiXYZ** [comment]
> If you can provide dev console and/or server errors and more details about your setup, I will do what I can to help.

Thank you very much. Here the datas:

> How did you build it: What database are you using? 

Ubuntu 20.04.3 LTS
openjdk 11.0.11 2021-04-20
node v16.13.0
@vue/cli 4.5.15
mariadb Ver 15.1 Distrib 10.3.31-MariaDB

>  Is your database running? 

yes

> Did you configure your .env file correctly? 

I think (and hope) so. Please see my Answers to @DearPureone in my initial post. There you find my `.env` file. I use (following the [knex](https://knexjs.org/) documentation) `DB_SOCKET='/var/run/mysqld/mysqld.sock'`, not HOST / PORT, because this is disabled by default in the`Ubuntu 20.04.3 LTS / MariaDB 15.1` configuration for security.

>  Most login issues are due to the database connection.

I do not think that that is the error. The database was created and exist with 25 records, I can see them via [adminer](https://www.adminer.org).
I got no errors when I started,

```
Nuxt @ v2.15.8                      │
   │                                       │
   │   ▸ Environment: development          │
   │   ▸ Rendering:   server-side          │
   │   ▸ Target:      static               │
   │                                       │
   │   Listening: http://localhost:3000/ 
```

only a warn message on the console: ["returning() is not supported by mysql and will not have any effect. "](https://github.com/knex/knex/blob/fdad316f01b15a25276effb30c304abdbd4e88ee/lib/dialects/mysql/query/mysql-querycompiler.js#L14) For me that is the evidence that the database is connected,  what do you say?

> After setup you can log in to 'admin@admin.com' with password 'beautifulHorseHippoAlgebra===9632'

Nop, No way. The response is `Error while logging in the User. Please try again later. `, no captcha.. The console says `.returning() is not supported by mysql and will not have any effect. `. No login.

The same with `User: joelbarish@mydomain.com, Password: joelbarish123 `... not working: `Error while logging in the User. Please try again later. `, no captcha.

> Then after logging in ....

This is what I am not reaching ... , unlike in your demo.


#  Try
I insert a new record via [adminer](https://www.adminer.org) in the `users` table with a new id, name, email, a (raw, not encrypted) password as admin and try to login with that. Surprising is I reached the captcha, and then the next captcha, then the next ... then the next ... then the next, but I am not logged in.


# Maybees

Maybe the decrypt / encrypt mechanism is not working with MariaDB and changes something or do not decrypt / encrypt?

Like @DearPureone  stated: I've test by this and login just fine on Postgres & MSSQL.

That leads to maybe the `knex` mysql/MariaDB driver is the problem, not using returning() because of mysql. I think it returns something different than expected.

Is that the problem? Is there a solution?

# Dankeschön (= Thank you)

Thanks for this great project and your fast response. Right on.

**Comment by adamlove01** [comment]
A fix for this has been pushed to master. Mysql and MariaDB had issues with `->returning()` in both the `insert()` and `update()` commands. Also, these databases will not accept ISO dates so that was fixed as well. Please let me know if you have any other issues. Thank you @RobbiXYZ and @DearPureone for reporting the errors!

**Comment by DearPureone** [comment]
it work as expect now
test on
Windows +  MariaDB +  Nuxt 2.15.8

as mention above a little issues i've found 
- on [reset password ](https://github.com/adamlove01/nuxt-ssr-secure-website/blob/2b66d0789f8702785366a4064fe837981d95a68d/server/controllers/loginController.js#L411) no  ' bcrypt function' so user can't login after reset password just add it
- after register success data was add to database but   the pop up that tell user is register success and e-mail confirmation not show after last update

**Comment by RobbiXYZ** [comment]
Yes, it work as expect now. 
test on
Ubuntu 20.04.3 LTS + MariaDB  15.1 +  Nuxt 2.15.8

Thank you very much @adamlove01 , @DearPureone
